name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  phpunit:
    name: Tests PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        laravel: ["7.*", "8.*"]
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: "8.*"
            php: 7.2
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ matrix.stability }}-${{ hashFiles('composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip
        coverage: none
      
    - name: Install dependencies
      run: |
        composer require "illuminate/support:${{ matrix.laravel }}" --${{ matrix.stability }} --prefer-dist --no-interaction

    - name: Run Testsuite
      run: ./vendor/bin/phpunit
    