name: Code-Style

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  php-code-style:
    name: Check PHP code style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-code-style-composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        extensions: dom, curl, libxml, mbstring, zip
        coverage: none
      
    - name: Install dependencies
      run: |
        composer update --prefer-stable --prefer-dist --no-interaction --no-progress

    - name: Run CS Fixer
      run: ./vendor/bin/php-cs-fixer fix --dry-run
    
    # - name: Commit changes
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: Fix styling
